import { RenameConfig } from '../types';

export const getDefaultConfig = (): RenameConfig => ({
  regexEnabled: false,
  regexMatch: '',
  regexReplace: '',
  regexIncludeExt: false,
  regexSimple: false,
  regexV2: false,

  nameEnabled: false,
  nameMode: 'keep',
  nameFixed: '',

  replaceEnabled: false,
  replaceFind: '',
  replaceWith: '',
  replaceMatchCase: false,

  caseEnabled: false,
  caseMode: 'lower',
  caseException: '',

  removeEnabled: false,
  removeFirst: 0,
  removeLast: 0,
  removeFrom: 0,
  removeTo: 0,
  removeChars: '',
  removeWords: false,
  removeCrop: 'none',
  removeCropText: '',
  removeAccents: false,
  removeSymbols: false,
  removeDigits: false,
  removeTrim: false,

  moveEnabled: false,
  moveMode: 'move',
  moveFrom: 0,
  moveTo: 0,
  moveLength: 0,
  movePosition: 0,
  moveSeparator: '',

  addEnabled: false,
  addPrefix: '',
  addSuffix: '',
  addInsert: '',
  addInsertAt: 0,

  dateEnabled: false,
  dateMode: 'prefix',
  dateType: 'modified',
  dateFormat: 'yyyy-MM-dd',
  dateSeparator: '_',
  dateCustom: '',

  folderEnabled: false,
  folderMode: 'prefix',
  folderLevels: 1,
  folderSeparator: '_',

  numberEnabled: false,
  numberMode: 'suffix',
  numberStart: 1,
  numberIncrement: 1,
  numberPad: 3,
  numberPosition: 0,
  numberSeparator: '_',
  numberCase: 'none',

  extEnabled: false,
  extMode: 'same',
  extFixed: '',
  extExtra: '',

  filterEnabled: false,
  filterMask: '*.*',
  filterRegex: '',
  filterMatchCase: false,
  filterFolders: false,
  filterFiles: true,
  filterHidden: false,
  filterMinSize: 0,
  filterMaxSize: 0,
  filterSubfolders: false,

  locationEnabled: false,
  locationMode: 'copy',
  locationPath: '',
  locationKeepStructure: false,

  specialEnabled: false,
  specialOrder: 'ascending',
  specialAttributes: false,
  specialTimestamps: false,
  specialJS: '',
});
